### ISSUE TITLE
请问能否添加一个新的规则？

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#247]
### issue 内容

ciyuancheng 这个播放源的网址似乎遭到攻击，因此网页端已经停止运作了，Kazumi里的规则应该也会跟着不可使用吧，因此请问能否添加一个新的域名的规则？就是这个 www.dmmiku.com

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这条规则应该已经有了，对应的名称应该是 yishijie

**Comment by bug333555** [comment]
> 这条规则应该已经有了，对应的名称应该是 yishijie

去试了一下，yishijie这个规则，在使用Kazumi内置播放器的情况下，一会会出现视频解析失败，一会会一直卡在转圈圈无法播放视频，不知道是没兼容好内置播放器，还是说是我自己的问题呢？我只有在关闭内置播放器的情况下，用网站自身的才能播放。

**Comment by Predidit** [comment]
我稍后看一下

**Comment by bug333555** [comment]
> 我稍后看一下

想问一下怎么样了？是内置播放器没兼容好的问题？还是说是我自己的问题呀？

**Comment by Predidit** [comment]
yishijie 的视频流怪怪的。

总之就是视频解析器是没问题的，但是解析出的 yishijie 视频流无法被 Android 原生多媒体套件 ExoPlayer 正确播放。在播放设置中禁用硬件解码可以解决此问题，但会导致一些其他视频无法播放。

具体细节我晚上再看看。

**Comment by Predidit** [comment]
`Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor, PngExtractor, WebpExtractor, BmpExtractor, HeifExtractor, AvifExtractor) could read the stream.{contentIsMalformed=false, dataType=1}`

我得到了这样的日志，问题在 Android ExoPlayer ，它没能正确解析视频流。但这本不应该发生，因为 ExoPlayer 对不同视频格式的兼容性相当棒。

我使用 ffmpeg 分析了这个视频流，日志如下

```
Input #0, hls, from 'https://json.bfdm.xyz/jsonapi.php?key=UWQONwVqA2kHM1c6BzwEYQY2VjBUIwdzUCQFZVNhCDpXZAQ%252FB2IAYAcwUT9TYQ%253D%253D&name=.m3u8':
  Duration: 00:24:26.13, start: 1.483422, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720, 23.98 fps, 23.98 tbr, 90k tbn
      Metadata:
        variant_bitrate : 0
  Stream #0:1(jpn): Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
      Metadata:
        variant_bitrate : 0
```

从流信息中可以看到，variant_bitrate 为 N/A，这意味着视频码率未定义，Android ExoPlayer 在这种情况下会拒绝播放。

我不知道 yishijie 出于什么理由在制作这种破坏移动设备多媒体组件兼容性的视频流，总之这种流只能在桌面设备上播放，或在移动设备上禁用硬件解码。这是 yishijie 的问题。

**Comment by bug333555** [comment]
> `Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor, PngExtractor, WebpExtractor, BmpExtractor, HeifExtractor, AvifExtractor) could read the stream.{contentIsMalformed=false, dataType=1}`
> 
> 我得到了这样的日志，问题在 Android ExoPlayer ，它没能正确解析视频流。但这本不应该发生，因为 ExoPlayer 对不同视频格式的兼容性相当棒。
> 
> 我使用 ffmpeg 分析了这个视频流，日志如下
> 
> ```
> Input #0, hls, from 'https://json.bfdm.xyz/jsonapi.php?key=UWQONwVqA2kHM1c6BzwEYQY2VjBUIwdzUCQFZVNhCDpXZAQ%252FB2IAYAcwUT9TYQ%253D%253D&name=.m3u8':
>   Duration: 00:24:26.13, start: 1.483422, bitrate: N/A
>   Program 0
>     Metadata:
>       variant_bitrate : 0
>   Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720, 23.98 fps, 23.98 tbr, 90k tbn
>       Metadata:
>         variant_bitrate : 0
>   Stream #0:1(jpn): Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
>       Metadata:
>         variant_bitrate : 0
> ```
> 
> 从流信息中可以看到，variant_bitrate 为 N/A，这意味着视频码率未定义，Android ExoPlayer 在这种情况下会拒绝播放。
> 
> 我不知道 yishijie 出于什么理由在制作这种破坏移动设备多媒体组件兼容性的视频流，总之这种流只能在桌面设备上播放，或在移动设备上禁用硬件解码。这是 yishijie 的问题。

原来是这样啊，看懂了，辛苦啦！
